#! /usr/bin/env python3
#-*- coding: UTF-8 -*-

# CC0 1.0 Unvanquished Developers
# https://creativecommons.org/publicdomain/zero/1.0/

import csv
import os
import sys

if len(sys.argv) < 2:
	exit(1)

file_name = sys.argv[1]
if not file_name.endswith(".tsv"):
	exit(1)

if not os.path.isfile(file_name):
	exit(1)

tsv_file = open(file_name, newline='')
tsv_reader = csv.reader(tsv_file, delimiter='\t')

print("<noinclude>{{Documentation}}</noinclude>")
print("{| class=\"wikitable\"")

header = []

for row in tsv_reader:
	print("|-")

	if row[-1] == "License":
		header = row
		markup = "!"
	else:
		markup = "|"

	for i in range(0, len(row)):
		cell = row[i]

		if header[i] == "License":
			cell = "{{{{nowrap|{}}}}}".format(cell)

		print("{} {}".format(markup, cell))

print("|}")

tsv_file.close()
